
import { GoogleGenAI, GenerateContentResponse, Type } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generateLevelMap = async (
  width: number,
  height: number,
  roomDensity: 'low' | 'medium' | 'high'
): Promise<any> => {
  const prompt = `
    Generate a JSON object representing a roguelike dungeon map.
    The map should be ${width} cells wide and ${height} cells tall.
    The room density should be ${roomDensity}.
    The JSON object must conform to the provided schema.
    Ensure there's a clear path from a start point to an end point.
    Include some treasure rooms.
    
    Cell Type Enum:
    - 0: Wall
    - 1: Floor
    - 2: Door
    - 3: Treasure
    - 4: Start Point
    - 5: End Point
  `;

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: "gemini-3-pro-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            level: {
              type: Type.ARRAY,
              description: "The main grid for the level layout.",
              items: {
                type: Type.ARRAY,
                items: {
                  type: Type.INTEGER,
                  description: "A cell in the grid, represented by an integer enum.",
                },
              },
            },
            width: { type: Type.INTEGER },
            height: { type: Type.INTEGER },
          },
          required: ["level", "width", "height"],
        },
      },
    });

    if (!response.text) {
      throw new Error("No text returned from API.");
    }

    const jsonText = response.text.trim();
    const parsed = JSON.parse(jsonText);
    
    if (!parsed.level || !Array.isArray(parsed.level)) {
       throw new Error("Parsed JSON missing 'level' array.");
    }

    return parsed;
  } catch (error) {
    console.error("Error generating level map:", error);
    // Re-throw so the UI receives the specific error message
    throw error;
  }
};

export const generateAssetConcept = async (prompt: string): Promise<string[]> => {
  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    const images: string[] = [];
    if (response.candidates && response.candidates.length > 0) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64EncodeString: string = part.inlineData.data;
          const imageUrl = `data:image/png;base64,${base64EncodeString}`;
          images.push(imageUrl);
        }
      }
    }
    if (images.length === 0) {
        // Fallback or specific error handling
        throw new Error("No images were generated by the API.");
    }
    return images;
  } catch (error) {
    console.error("Error generating asset concept:", error);
    throw new Error("Failed to generate asset concept from Gemini API.");
  }
};

export const generateNarrative = async (
  context: string,
  type: string,
  tone: string
): Promise<string> => {
  const prompt = `
    You are AetherNarrative, an AI Director for a game.
    Generate game content of type: "${type}".
    Context/Prompt: "${context}".
    Tone: "${tone}".
    
    Output purely the content (dialogue, lore description, or quest text) without meta-commentary.
  `;

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: "gemini-3-pro-preview",
      contents: prompt,
    });
    return response.text || "No narrative generated.";
  } catch (error) {
    console.error("Error generating narrative:", error);
    throw new Error("Failed to generate narrative.");
  }
};
